repos:
  - repo: local
    hooks:
      - id: test
        name: Test PackBits compression/decompression
        entry: deno test
        language: system
        files: mod(\.test)?\.ts$
        pass_filenames: false
